ZLERP.Web/Controllers/GoodsAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZLERP.Model;
using ZLERP.Web.Helpers;

namespace ZLERP.Web.Controllers
{
    public class GoodsAccountController : BaseController<GoodsAccount, int?>
    {
        public override ActionResult Index()
        {
            //ViewBag.StuffList = HelperExtensions.SelectListData<StuffInfo>("StuffName", "ID", "StuffName", true);
            ViewBag.StuffList = HelperExtensions.SelectListData<StuffInfo>("StuffName",
                "ID",
                "IsUsed=1",
                "StuffName",
                true, "");

            return base.Index();
        }
    }
}

ZLERP.Web/Controllers/SiloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZLERP.Model;
using ZLERP.Web.Helpers;

namespace ZLERP.Web.Controllers
{
    public class SiloController : BaseController<Silo,string>
    {
        public override System.Web.Mvc.ActionResult Index()
        {
            //原材料列表
            var parentStuffInfo = this.service.GetGenericService<StuffInfo>().All("", "OrderNum", true).Where(s => s.IsUsed).ToList();
            parentStuffInfo.Insert(0, new StuffInfo());
            ViewBag.StuffInfoDics = new SelectList(parentStuffInfo, "ID", "StuffName");
            
            //机组信息列表
            var pllist=HelperExtensions.SelectListData<ProductLine>("ProductLineName", "ID", "IsUsed=1", "ID", true, "");
            ViewBag.ProductLineList = pllist;

            return base.Index();
        }
        /// <summary>
        /// 筒仓列表数据【格式：筒仓名称（筒仓简称）】
        /// </summary>
        /// <param name="textField"></param>
        /// <param name="valueField"></param>
        /// <param name="orderBy"></param>
        /// <param name="ascending"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        public override JsonResult ListData(string textField, string valueField, string orderBy = "ID",
            bool ascending = false,
            string condition = "")
        {
            var data = this.m_ServiceBase.All(new List<string> { valueField, textField, "SiloShortName" }, condition, orderBy, ascending);
            foreach (var d in data) {
                d.SiloName = string.Format("{0}({1})", d.SiloName, d.SiloShortName);
            }
            return Json(new SelectList(data, valueField, textField));
        }
        /// <summary>
        /// 桶仓库存状态
        /// </summary>
        /// <returns></returns>
        public ActionResult SiloStatus()
        {
            base.InitCommonViewBag();
            var siloList = this.service.Silo.All("OrderNum", true);
            ViewBag.ProductLine = this.service.ProductLine.Query().Where(p=>p.IsUsed).ToList();
            ViewBag.SiloProductLine = this.service.GetGenericService<SiloProductLine>().All().OrderBy(m=>m.Silo.OrderNum);
            return View(siloList);
        }

    }
}

ZLERP.Web/Views/GoodsAccount/Index.cshtml
@model ZLERP.Model.GoodsAccount 
@section HeaderSection{
<script src="@Url.Content("~/Scripts/Views/GoodsAccount/GoodsAccount.js")" type="text/javascript" language="javascript"> </script>
    <script type="text/javascript">
        IndexInit({
            storeUrl: '@Url.Action("Find")',
            findSiloUrl: '@Html.Raw(Url.Action("ListData", "Silo", new {textField="SiloName", valueField="ID"}))'
        });
</script>
}

<!-- 左边Grid -->
<div id="MyJqGridMain" style="float: left; width: 35%">
</div>

<!-- 右边Grid -->
<div id="MyJqGrid" style="float: right; width: 64%">
</div>

<div id="MyFormDivMain" class="mvcform" style="display:none;">
@using (Html.BeginForm())
    {@Html.ValidationSummary()
    <table class="mvcform"> 
        <tr> 
            <td >@Html.Hidden("ID")
           </td>
        </tr>
        <tr> 
            <td>@Html.Label("月份")@*@Html.Editor("Month", "", new {@data_val_required = "月份 字段是必需的", data_val = "true", defaultValue = @DateTime.Now.ToString("yyyyMM") })*@
            <select id="Month" name="Month">
               <option value="201601">201601</option>
               <option value="201602">201602</option>
               <option value="201603">201603</option>
               <option value="201604">201604</option>
               <option value="201605">201605</option>
               <option value="201606">201606</option>
               <option value="201607">201607</option>
               <option value="201608">201608</option>
               <option value="201609">201609</option>
               <option value="201610">201610</option>
               <option value="201611">201611</option>
               <option value="201612">201612</option>
               <option value="201701">201701</option>
               <option value="201702">201702</option>
               <option value="201703">201703</option>
               <option value="201704">201704</option>
               <option value="201705">201705</option>
               <option value="201707">201707</option>
               <option value="201707">201707</option>
               <option value="201708">201708</option>
               <option value="201709">201709</option>
               <option value="201710">201710</option>
               <option value="201711">201711</option>
               <option value="201712">201712</option>
            </select>
            </td>
        </tr>
        <tr> 
            <td>@Html.Label("备  注")@Html.TextBox("Meno", "", new { })</td>
        </tr>
    </table>

    }
</div>

<div id="MyFormDiv" class="mvcform" style="display:none;">
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary()
        @Html.Hidden("ID")
        <table class="mvcform"> 
            <tr>
                <td>@Html.LabelFor(m => m.GoodsId)@Html.AutoComplete("GoodsId", "GoodsName", "Combo", "GoodsInfo", "ID", "GoodsName", "isused=1", new { style = "width:102px" })</td>

                @*<td>@Html.LabelFor(m => m.StuffId)@Html.AutoComplete("StuffId", "StuffName", "Combo", "StuffInfo", "ID", "StuffName")
                </td>*@
            </tr>
            <tr>
                
                <td>@Html.LabelFor(m => m.CurrentCount)@Html.EditorFor(m => m.CurrentCount)
                </td>
                 <td>@Html.LabelFor(m => m.CurrentMoney)@Html.EditorFor(m => m.CurrentMoney)
                </td>
            </tr>
            <tr>
                <td>@Html.LabelFor(m => m.Meno)@Html.EditorFor(m => m.Meno)
                </td>
            </tr>
            <tr> 
            <td style="display: none">@Html.LabelFor(m => m.GoodsAccountMainId)@Html.EditorFor(m => m.GoodsAccountMainId)</td>
   
        </tr>
    </table>

    }
</div>