ZLERP.Web/Controllers/EquipMtLyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Script.Serialization;
using ZLERP.Model;
using System.Web;
using System.Web.Mvc;
using ZLERP.Web.Helpers;
using ZLERP.Resources;
using ZLERP.Business;

namespace ZLERP.Web.Controllers
{
    public class EquipMtLyController : BaseController<EquipMtLy, string>
    {
        public override ActionResult Index()
        {
            ViewBag.MntZlID = HelperExtensions.SelectListData<MntZl>("ID", "ID", "MntZlID IN (SELECT DISTINCT MntZlID FROM MntZlItem) AND ReAuditStatus = 1","ID",true,"");
            ViewBag.ClassBEquip = HelperExtensions.SelectListData<ClassB>("ClassBName", "ID", "ClassID ='" + Request.QueryString["p1"] + "'", "ID", true, "");
            ViewBag.Department = HelperExtensions.SelectListData<Department>("DepartmentName", "ID", "", "ID", true, "");
            ViewBag.User = HelperExtensions.SelectListData<User>("TrueName", "ID", "", "ID", true, "");
            ViewBag.PartInfo = HelperExtensions.SelectListData<PartInfo>("PartName", "ID", "", "ID", true, "");
            return base.Index();
        }

        public ActionResult Apply()
        {
            ViewBag.ClassBEquip = HelperExtensions.SelectListData<ClassB>("ClassBName", "ID", "ClassID ='EquipType'", "ID", true, "");
            ViewBag.Department = HelperExtensions.SelectListData<Department>("DepartmentName", "ID", "", "ID", true, "");
            ViewBag.User = HelperExtensions.SelectListData<User>("TrueName", "ID", "", "ID", true, "");
            InitCommonViewBag();
            return View();
        }
        public override ActionResult Add(EquipMtLy EquipMtLy)
        {
            EquipMtLy.mtlystate = 0;
            return base.Add(EquipMtLy);
        }

        public override ActionResult Update(EquipMtLy EquipMtLy)
        {
            EquipMtLy.mtlystate = 0;
            return base.Update(EquipMtLy);
        }

        public ActionResult ImportEntitys(string equipmtlyid, string[] ids) {
            try
            {
                this.service.EquipMtLyService.ImportMntZlItems(equipmtlyid, ids);
                return OperateResult(true, Lang.Msg_Operate_Success, "");
            }
            catch (Exception e)
            {
                if (e.InnerException != null)
                    e = e.InnerException;
                log.Error(e.Message, e);
                return OperateResult(false, Lang.Msg_Operate_Failed + ":" + (e.Message.Contains("UNIQUE KEY") == true ? Lang.IsExistRecord : e.Message), null);
            }
        }

        public ActionResult submit(string id)
        {
            EquipMtLy e = this.m_ServiceBase.Get(id);
            e.mtlystate = 1;
            base.Update(e);

            PurchasePlanByEquip obj = new PurchasePlanByEquip();
            obj.PurchasePlan_NeedDate = e.ApplyTime;
            obj.GoodsID = e.EquipmentName;
            //obj.BID = e.ClassBID;
            //obj.MID = e.ClassMID;
            //obj.SID = e.ClassSID;
            obj.PurchasePlan_reason = e.TroubleDes;
            obj.PurchasePlan_planstate = 0;
            obj.PurchasePlan_state = 0;
            obj.PurchasePlan_claimer = AuthorizationService.CurrentUserID;
            obj.planmoney = 0.00m;
            obj._type = 0;
            obj.planmoney = e.summoney;
            obj.EquipMtLyID = id;

            this.service.PurchasePlanByEquip.Add(obj);

            return OperateResult(true, Lang.Msg_Operate_Success, null); 
        }
    }    
}

ZLERP.Web/Controllers/MntZlController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ZLERP.Web.Controllers.Attributes;
using ZLERP.Model;
using System.Linq;
using ZLERP.Web.Helpers;
using ZLERP.Resources;
using ZLERP.Business;

namespace ZLERP.Web.Controllers
{
    public class MntZlController : BaseController<MntZl, string>
    {
        public override System.Web.Mvc.ActionResult Index()
        {
            ViewBag.PartType = Request.QueryString["p1"];
            ViewBag.Users = HelperExtensions.SelectListData<User>("TrueName", "ID", "", "ID", true, "");
            ViewBag.Departments = HelperExtensions.SelectListData<Department>("DepartmentName", "ID", "", "ID", true, "");
            ViewBag.ClassBPart = HelperExtensions.SelectListData<ClassB>("ClassBName", "ID", "ClassID ='" + Request.QueryString["p1"] + "'", "ID", true, "");
            ViewBag.ClassMPartInit = HelperExtensions.SelectListData<ClassM>("ClassMName", "ID", "ClassID ='" + Request.QueryString["p1"] + "'", "ID", true, "");
            ViewBag.ClassSPartInit = HelperExtensions.SelectListData<Classs>("ClassSName", "ID", "ClassID ='" + Request.QueryString["p1"] + "'", "ID", true, "");
            ViewBag.PartInfo = HelperExtensions.SelectListData<PartInfo>("PartName","ID","","ID",true,"");
            ViewBag.ClassB = HelperExtensions.SelectListData<ClassB>("ClassBName", "ID", "ClassID ='EquipType'", "ID", true, "");
            return base.Index();
        }
        public override ActionResult Add(MntZl MntZl)
        {
            return base.Add(MntZl);
        }

        public override ActionResult Update(MntZl MntZl)
        {
            if (ModelState.IsValid)
            {
                return base.Update(MntZl);
            }
            else {
                var m = ModelState.Values.Where(p => p.Errors.Count > 0)
                    .Select(c => string.Join(",", c.Errors.Select(p => p.ErrorMessage).ToList())).ToList();

                return OperateResult(false, string.Join("<br/>", m), null);
            }
        }

        //审核
        public ActionResult Audit(MntZl MntZl) {
            try
            {
                this.service.MntZl.Audit(MntZl);
                
                this.service.SysLog.Log(Model.Enums.SysLogType.Audit, MntZl.ID, null, "设备支领审核");
                return OperateResult(true, Lang.Msg_Operate_Success, null);
            }
            catch (Exception e)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed + e.Message, null);
            }
        }


        //经理审核
        public ActionResult ManageAudit(MntZl MntZl)
        {
            try
            {
                this.service.MntZl.ManageAudit(MntZl);
                if (MntZl.ReAuditStatus == 1)
                {
                    IList<MntZlItem> mntZlItemList = this.service.GetGenericService<MntZlItem>().All("MntZlID= '" + MntZl.ID + "'", "MntZlID", true);
                    if (mntZlItemList != null)
                    {
                        ServiceBase<PartInfo> partInfoService = this.service.GetGenericService<PartInfo>();
                        foreach (MntZlItem mntZlItem in mntZlItemList)
                        {
                            PartInfo partInfo = partInfoService.Get(mntZlItem.PartID);
                            if (mntZlItem.amount != null)
                            {
                                partInfo.Inventory -= (int)mntZlItem.amount;

                                if (partInfo.Inventory < 0)
                                {
                                    string str = String.Format("领用数量{0}大于当前库存量，审核不通过！", mntZlItem.amount);
                                    return OperateResult(false, str, false);
                                }
                            }
                            partInfoService.Update(partInfo, null);
                        }
                    }
                }
                this.service.SysLog.Log(Model.Enums.SysLogType.Audit, MntZl.ID, null, "设备支领审核");
                return OperateResult(true, Lang.Msg_Operate_Success, null);
            }
            catch (Exception e)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed + e.Message, null);
            }
        }

        //批次审核
        public override ActionResult BatchAudit(string[] ids) {
            try
            {
                this.service.MntZl.BatchAudit(ids);
                this.service.SysLog.Log(Model.Enums.SysLogType.Audit, ids.ToString(), null, "设备支领批次审核");
                return OperateResult(true, Lang.Msg_Operate_Success, null);
            }
            catch (Exception e)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed + e.Message, null);
            }
        }

        /*
         * 批次审核页面
         */
        public virtual ActionResult AuditBatch() {
            return View();
        }
    }    
}

ZLERP.Web/Views/EquipMtLy/Apply.cshtml
@model ZLERP.Model.EquipMtLy
@section HeaderSection{
<script src="@Url.Content("~/Scripts/Views/EquipMtLy/ApplyEquipMtLy.js")" type="text/javascript" language="javascript"> </script>
    <script type="text/javascript">
        $(function () {
            equipmtlyIndexInit({
                storeUrl: '@Url.Action("Find")',
                listClassMUrl: '@Url.Action("ListData","ClassM")',
                listClassSUrl: '@Url.Action("ListData","ClassS")',
                listEquipUrl: '@Url.Action("ListData","Equipment")'
            });
        });
    </script>
}
<div id="EquipMtLyGrid"></div>
<div id="EquipMtLyForm" class="mvcform" style="display:none;">
@using (Html.BeginForm())
{@Html.ValidationSummary()
@Html.TextBoxFor(m => m.ID, new { style = "display:none;" })
<table class="mvcform"> 
    <tr> 
        <td>@Html.LabelFor(m => m.ClassBID)@Html.DropDownListFor(m => m.ClassBID, ViewBag.ClassBEquip as IEnumerable<SelectListItem>, new { style = "width:138px;" })</td>
        <td>@Html.LabelFor(m => m.ClassMID)@Html.DropDownListFor(m => m.ClassMID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.ClassSID)@Html.DropDownListFor(m => m.ClassSID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
        <td>@Html.LabelFor(m => m.EquipmentID)@Html.DropDownListFor(m => m.EquipmentID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.Finder)@Html.EditorFor(m => m.Finder)</td>
        <td>@Html.LabelFor(m => m.FindTime)@Html.EditorFor(m => m.FindTime, "DateTime", new { DefaultValue = @DateTime.Now.ToString("yyyy-MM-dd") })</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.ApplyMan)@Html.EditorFor(m => m.ApplyMan)</td>
        <td>@Html.LabelFor(m => m.ApplyTime)@Html.EditorFor(m => m.ApplyTime, "DateTime", new { DefaultValue = @DateTime.Now.ToString("yyyy-MM-dd") })</td>
    </tr>
    <tr>
    <td>@Html.LabelFor(m => m.MtDate)@Html.EditorFor(m => m.MtDate, "DateTime", new { DefaultValue = @DateTime.Now.ToString("yyyy-MM-dd") })</td>
    <td>@Html.LabelFor(m=>m.summoney)@Html.TextBoxFor(m=>m.summoney)</td>
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.TroubleDes)@Html.TextAreaFor(m => m.TroubleDes, 3, 50, new { })</td>   
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.RepairAdv)@Html.TextAreaFor(m => m.RepairAdv, 3, 50, new { })</td>   
    </tr>
</table>

}
</div>

ZLERP.Web/Views/EquipMtLy/Index.cshtml
@model ZLERP.Model.ViewModels.EquipMtLyAndItem 
@section HeaderSection{
<script src="@Url.Content("~/Scripts/Views/EquipMtLy/EquipMtLy.js")" type="text/javascript" language="javascript"> </script>
    <script type="text/javascript">
        $(function () {
            equipmtlyIndexInit({
                storeUrl: '@Url.Action("Find")',
                equipMtLyAddUrl: '@Url.Action("Add")',
                equipMtLyUpdateUrl: '@Url.Action("Update")',
                itemStoreUrl:'@Url.Action("Find","EquipMtLyItem")',
                listClassMUrl: '@Url.Action("ListData","ClassM")',
                listClassSUrl: '@Url.Action("ListData","ClassS")',
                listEquipUrl: '@Url.Action("ListData","Equipment")',
                listMaintenanceUrl: '@Url.Action("ListData","Maintenance")',
                getMntZlByIdUrl: '@Url.Action("Get","MntZl")',
                MntZlItemstoreUrl: '@Url.Action("Find","MntZlItem")',
                classTypeID: '@Request.QueryString["p1"]'

            });
        });
    </script>
}
<div id="EquipMtLyGrid" style=" float:left; width:40%"></div>
<div id="EquipMtLyItemGrid" style=" float:right; width:59.8%"></div>
<div id="EquipMtLyForm" class="mvcform" style="display:none;">
@using (Html.BeginForm())
{@Html.ValidationSummary()
@Html.TextBoxFor(m => m.EquipMtLy.ID, new { style = "display:none;" })
@Html.TextBoxFor(m => m.EquipMtLy.YM, new { Value = @DateTime.Now.ToString("yyyy-MM"), style = "display:none;" })
@Html.TextBox("actiontype", "add", new {style="display:none;" })
<table class="mvcform"> 
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.MntZlID)@Html.DropDownListFor(m => m.EquipMtLy.MntZlID, ViewBag.MntZlID as IEnumerable<SelectListItem>, new { style="width:138px;"})</td>
        <td>@Html.LabelFor(m => m.EquipMtLy.MtDate)@Html.EditorFor(m => m.EquipMtLy.MtDate, "DateTime", new { DefaultValue = @DateTime.Now.ToString("yyyy-MM-dd") })</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.ClassBID)@Html.DropDownListFor(m => m.EquipMtLy.ClassBID, ViewBag.ClassBEquip as IEnumerable<SelectListItem>, new { style = "width:138px;" })</td>
        <td>@Html.LabelFor(m => m.EquipMtLy.ClassMID)@Html.DropDownListFor(m => m.EquipMtLy.ClassMID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.ClassSID)@Html.DropDownListFor(m => m.EquipMtLy.ClassSID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
        <td>@Html.LabelFor(m => m.EquipMtLy.EquipmentID)@Html.DropDownListFor(m => m.EquipMtLy.EquipmentID, Enumerable.Empty<SelectListItem>(), new { style = "width:138px;" })</td>
    </tr>

    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.TyreID)@Html.EditorFor(m => m.EquipMtLy.TyreID)</td>
        <td>@Html.LabelFor(m => m.EquipMtLy.IsEntrust)@Html.CheckBoxFor(m => m.EquipMtLy.IsEntrust)</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.ContractID)@Html.AutoComplete("EquipMtLy.ContractID", "EquipMtLy.ContractName", "Combo", "Contract", "ID", "ContractName")</td>
        <td rowspan="2" style="padding-left:28px;"><button class="tbtn ui-icon-arrowreturnthick-1-e" onclick="importZlItems();return false;">导入支领明细</button></td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLy.Remark)@Html.TextAreaFor(m => m.EquipMtLy.Remark, 3, 18, new { })</td>
   
    </tr>
</table>

}
</div>

<div id="EquipMtLyItemForm" class="mvcform" style="display:none;">
@using (Html.BeginForm())
{@Html.ValidationSummary()
@Html.Hidden("classbid","")
@Html.TextBoxFor(m => m.EquipMtLyItem.ID, new { style = "display:none;" })
<table class="mvcform"> 
    <tr> 
        <td style="color:Blue;">@Html.LabelFor(m => m.EquipMtLyItem.EquipMtLyID)@Html.EditorFor(m => m.EquipMtLyItem.EquipMtLyID)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.Amount)@Html.EditorFor(m => m.EquipMtLyItem.Amount)@*@Html.LabelFor(m => m.EquipMtLyItem.MaintenanceID)@Html.DropDownListFor(m => m.EquipMtLyItem.MaintenanceID, Enumerable.Empty<SelectListItem>())*@</td>
    </tr>
    @*<tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.PartID)@Html.DropDownListFor(m => m.EquipMtLyItem.PartID, ViewBag.PartInfo as IEnumerable<SelectListItem>)</td>
        <td></td>
    </tr>*@
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.PurposeMill)@Html.DicEditorFor(m => m.EquipMtLyItem.PurposeMill, DicEnum.PartApplication)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.IsAssess)@Html.CheckBoxFor(m => m.EquipMtLyItem.IsAssess)</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.DepartmentID)@Html.DropDownListFor(m => m.EquipMtLyItem.DepartmentID, ViewBag.Department as IEnumerable<SelectListItem>)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.UserID)@Html.DropDownListFor(m => m.EquipMtLyItem.UserID, ViewBag.User as IEnumerable<SelectListItem>)</td>
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.EquipMtLyItem.Remark)@Html.TextAreaFor(m => m.EquipMtLyItem.Remark, 1, 50, new { })</td>
    </tr>
</table>

}
</div>

<div id="AddEquipMtLyItemForm" class="mvcform" style="display:none;">
@using (Html.BeginForm())
{@Html.ValidationSummary()
<table class="mvcform"> 
    <tr> 
        <td style="color:Blue;">@Html.LabelFor(m => m.EquipMtLyItem.EquipMtLyID)@Html.EditorFor(m => m.EquipMtLyItem.EquipMtLyID)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.Amount)@Html.EditorFor(m => m.EquipMtLyItem.Amount)@*@Html.LabelFor(m => m.EquipMtLyItem.MaintenanceID)@Html.DropDownListFor(m => m.EquipMtLyItem.MaintenanceID, Enumerable.Empty<SelectListItem>(), new { id = "Add_EquipMtLyItem_MaintenanceID" })*@</td>
    </tr>
    @*<tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.PartID)@Html.DropDownListFor(m => m.EquipMtLyItem.PartID, ViewBag.PartInfo as IEnumerable<SelectListItem>)</td>
        <td></td>
    </tr>*@
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.PurposeMill)@Html.DicEditorFor(m => m.EquipMtLyItem.PurposeMill, DicEnum.PartApplication)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.IsAssess)@Html.CheckBoxFor(m => m.EquipMtLyItem.IsAssess)</td>
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.EquipMtLyItem.DepartmentID)@Html.DropDownListFor(m => m.EquipMtLyItem.DepartmentID, ViewBag.Department as IEnumerable<SelectListItem>)</td>
        <td>@Html.LabelFor(m => m.EquipMtLyItem.UserID)@Html.DropDownListFor(m => m.EquipMtLyItem.UserID, ViewBag.User as IEnumerable<SelectListItem>)</td>
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.EquipMtLyItem.Remark)@Html.TextAreaFor(m => m.EquipMtLyItem.Remark, 1, 50, new { })</td>
    </tr>
</table>

}
</div>

@*导入支领明细弹出框*@
<div id="ImportMntZlItemForm" style="display:none;">
    <div id="MntZlItemGrid"></div>
</div>