ZLERP.Web/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZLERP.Model;
using Lib.Web.Mvc.JQuery.JqGrid;
using ZLERP.Resources;
using ZLERP.Web.Helpers;
using ZLERP.Model.Enums;

namespace ZLERP.Web.Controllers
{
    public class CarController : BaseController<Car,string>
    {
        public override ActionResult Index()
        {
            ViewBag.DepartmentList = HelperExtensions.SelectListData<Department>("DepartmentName", "ID", "", "DepartmentName", true, "");
            //ViewBag.UserList = HelperExtensions.SelectListData<User>("TrueName", "ID", "IsUsed=1 AND (UserType ='" + UserType.Driver + "' OR UserType ='" + UserType.MixerDriver + "')", "TrueName", true, "");
            ViewBag.CarClassList = HelperExtensions.SelectListData<CarClass>("CarClassName", "ID", "", "CarClassName", true, "");

            var parentCompany = this.service.GetGenericService<Company>().All("", "ID", true);
            ViewBag.CompanyDics = new SelectList(parentCompany, "ID", "CompName");
            //ViewBag.CompanyList = HelperExtensions.SelectListData<Company>("CompName", "ID", "", "CompName", true, "");
            return base.Index();
        }

        [HttpPost]
        public override ActionResult Add(Car car)
        {            
            ActionResult result = base.Add(car);
            AddCarHistory(car, result);
            return result;
        }
        [HttpPost]
        public override ActionResult Update(Car car)
        {
            ActionResult result = base.Update(car);
            AddCarHistory(car, result);
            return result;
        }

        [HttpPost]
        public override ActionResult Delete(string[] id)
        {
            ActionResult result = base.Delete(id);
            DeleCarHistory(id, result);
            return result;
        }

        /// <summary>
        /// 添加历史记录
        /// </summary>
        /// <param name="car"></param>
        /// <param name="result"></param>
         private void AddCarHistory(Car car,ActionResult result)
         {
             if (!string.IsNullOrEmpty(car.ID) && (((ResultInfo)((JsonResult)result).Data).Result))
             {
                 //获得最后一条的历史数据
                 CarHistory carHistory = this.service.CarHistory.GetLastData(car.ID);
                 if (carHistory != null)
                 {
                     if (carHistory.CarWeight == car.CarWeight)
                     {
                         //未修改皮重 不增加历史记录
                         return;
                     }
                 }

                 CarHistory _CarHistory = new CarHistory();
                 _CarHistory.BelongTo = car.BelongTo;
                 _CarHistory.Builder = car.Builder;
                 _CarHistory.BuildTime = car.BuildTime;
                 _CarHistory.BuyDate = car.BuyDate;
                 _CarHistory.CarClass = car.CarClass;
                 _CarHistory.CarClassID = car.CarClassID;
                 //_CarHistory.CarClassName = car.CarClassName;
                 _CarHistory.CarID = car.ID;
                 _CarHistory.CarNo = car.CarNo;
                 _CarHistory.CarStatus = car.CarStatus;
                 _CarHistory.CarTypeID = car.CarTypeID;
                 _CarHistory.CarWeight = car.CarWeight;
                 _CarHistory.ChassisID = car.ChassisID;
                 _CarHistory.DriverForCars = car.DriverForCars;
                 _CarHistory.EngineID = car.EngineID;
                 _CarHistory.FacInnerID = car.FacInnerID;
                 _CarHistory.Factory = car.Factory;
                 _CarHistory.GPSStatus = car.GPSStatus;
                 _CarHistory.IsUsed = car.IsUsed;
                 _CarHistory.LastBackTime = car.LastBackTime;
                 _CarHistory.LeaveFacDate = car.LeaveFacDate;
                 _CarHistory.Lifecycle = car.Lifecycle;
                 _CarHistory.MaxCube = car.MaxCube;
                 _CarHistory.Modifier = car.Modifier;
                 _CarHistory.ModifyTime = DateTime.Now;
                 _CarHistory.OilConsume = car.OilConsume;
                 _CarHistory.OrderNum = car.OrderNum;
                 _CarHistory.Owner = car.Owner;
                 _CarHistory.PumpTypeID = car.PumpTypeID;
                 _CarHistory.Remark = car.Remark;
                 _CarHistory.RentCarName = car.RentCarName;
                 _CarHistory.SIM = car.SIM;
                 _CarHistory.StuffWeight = car.StuffWeight;
                 _CarHistory.TerminalID = car.TerminalID;
                 _CarHistory.Version = car.Version;
                 _CarHistory.CompanyID = car.CompanyID;

                 this.service.CarHistory.Add(_CarHistory);
             }
         }
        /// <summary>
         /// 删除历史记录
        /// </summary>
        /// <param name="id"></param>
        /// <param name="result"></param>
         private void DeleCarHistory(string[] id, ActionResult result)
         {
             if (id == null) return;
             if (((ResultInfo)((JsonResult)result).Data).Result)
             {
                 for (int i = 0; i < id.Length; i++)
                 {
                     //查找此车下属的历史信息
                     string[] ids = this.service.CarHistory.GetHistoryIDByCarID(id[i]);
                     if (ids == null || ids.Length == 0)
                         continue;
                     this.service.CarHistory.Delete(ids);
                 }
             }
         }

        /// <summary>
        /// 根据car获取司机、容重等。调度使用。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetInfo(string id)
        {
            dynamic car = this.service.Car.GetInfo(id);
            return this.Json(car);
        }


        /// <summary>
        /// 获取车辆信息，根据状态进行分组
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetMixerCarStatus()
        {
            dynamic car = this.service.Car.GetMixerCarStatus();
            return this.Json(car);
        }

        /// <summary>
        /// 修改车辆状态，调度界面使用。
        /// </summary>
        /// <param name="operType"></param>
        /// <param name="carId"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        public ActionResult ShiftMixerCarStatus(string operType, string carId, string status) 
        {
            this.service.Car.ShiftMixerCarStatus(operType, carId, status);
            return OperateResult(true, Lang.Msg_Operate_Success, null);
        }

        /// <summary>
        /// 拖放搅拌车操作
        /// </summary>
        /// <param name="carid"></param>
        /// <param name="orders"></param>
        /// <returns></returns>
        public ActionResult DragMixerCar(string carid, string[] orders)
        {
            try
            {
                this.service.Car.DragMixerCar(carid, orders);
                return OperateResult(true, Lang.Msg_Operate_Success, null);
            }
            catch (Exception)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed, null);
            }
        }

        /// <summary>
        /// 明天可用车辆
        /// </summary>
        /// <param name="availableCar">可用车辆</param>
        /// <param name="carNum">车辆总数</param>
        /// <returns></returns>
        public ActionResult AddAvailableCar(string availableCar, string carNum)
        {
            try
            {
                this.service.Car.AddAvailableCar(availableCar, carNum);
                return OperateResult(true, Lang.Msg_Operate_Success, null);

            }
            catch (Exception e)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed + e.Message, null);
            }
        }

        /// <summary>
        /// GPS车辆状态修改
        /// </summary>
        /// <param name="id"></param>
        /// <param name="code"></param>
        /// <returns></returns>
        public ActionResult GPSChangeCarStatus(string id, string code)
        {
            try
            {
                this.service.Car.GPSChangeCarStatus(id, code);
                return OperateResult(true, Lang.Msg_Operate_Success, null);
            }
            catch (Exception e)
            {
                return OperateResult(false, Lang.Msg_Operate_Failed + e.Message, null);
            }
        }

    }
}

ZLERP.Web/Controllers/PumpWorkController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Script.Serialization;
using ZLERP.Model;
using System.Web;
using System.Web.Mvc;
using ZLERP.Resources;

namespace ZLERP.Web.Controllers
{
    public class PumpWorkController : BaseController<PumpWork, string>
    {
        public override System.Web.Mvc.ActionResult Add(PumpWork entity)
        {
            //先检测任务单的发货数量与已泵数量
            //此处以发货单的数据为准，以后调研后进行修改
            try
            {
                string taskId = entity.TaskID;
                this.service.PumpWork.CompareShipAndPump(entity);
                return base.Add(entity);
                
            }
            catch (Exception e) {
                return OperateResult(false, e.Message, null);
            }
            
            
        }

        public override System.Web.Mvc.ActionResult Update(PumpWork entity)
        {
            //先检测任务单的发货数量与已泵数量
            try {
                this.service.PumpWork.CompareShipAndPump(entity);
                return base.Update(entity);
            
            }catch(Exception e){
                return OperateResult(false, e.Message, null);
            }
            
        }

        public ActionResult getPumpTypeAndPumpCost(string taskId, DateTime? pumpDate) {
            dynamic pumpTypeAndCostInfo = this.service.PumpWork.getPumpTypeAndPumpCost(taskId,pumpDate);

            return this.Json(pumpTypeAndCostInfo);
        }
    }    
}

ZLERP.Web/Views/PumpWork/Index.cshtml
@model ZLERP.Model.PumpWork 
@section HeaderSection{
<script src="@Url.Content("~/Scripts/Views/PumpWork.js")" type="text/javascript" language="javascript"> </script>
    <script type="text/javascript">
        $(function () {
            pumpworkIndexInit({
                pumpWorkStoreUrl:'@Url.Action("Find")',
                listContractUrl:'@Url.Action("ListData", "Contract")',
                listTaskUrl:'@Url.Action("ListData", "ProduceTask")',
                listCarUrl: '@Url.Action("ListData", "Car")',
                getPumpTypeCostStoreUrl: '@Url.Action("getPumpTypeAndPumpCost")'
            });
        });
</script>
}
<div id="PumpWorkGrid"></div>
<div id="pumpworkform" class="mvcform" style="display:none;">
@using (Html.BeginForm())
{@Html.ValidationSummary()
<table class="mvcform"> 
    <tr> 
        <td>@Html.TextBoxFor(m => m.ID, new { @class = "text", style = "display:none;" })
        @Html.LabelFor(m => m.Customer.CustName)@Html.AutoCompleteFor(m => m.CustomerID, m => m.Customer.CustName, "Combo", "Customer", "ID", "CustName", new { @class = "text" })
        </td>
        <td>@Html.LabelFor(m => m.Saler)@Html.EditorFor(m => m.Saler)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.Contract.ContractName)@Html.DropDownListFor(m => m.ContractID, Enumerable.Empty<SelectListItem>(), new { @class = "text", style = "width:137px;" })</td>
 
        <td>@Html.LabelFor(m => m.PumpDate)@Html.EditorFor(m => m.PumpDate, "DateTime", new { defaultValue = @DateTime.Now.ToString("yyyy-MM-dd") })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.TaskID)@Html.DropDownListFor(m => m.TaskID, Enumerable.Empty<SelectListItem>(), new { @class = "text", style = "width:137px;" })</td>
 
        <td>@Html.LabelFor(m => m.PumpType)@Html.DicEditorFor(m => m.PumpType, DicEnum.PumpType, "")</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.CarID)@Html.DropDownListFor(m => m.CarID, Enumerable.Empty<SelectListItem>(), new { @class = "text", style = "width:137px;" })</td>
 
        <td>@Html.LabelFor(m => m.Driver)@Html.EditorFor(m => m.Driver)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.CustNum)@Html.TextBoxFor(m => m.CustNum, new { Value = 0 })</td>
 
        <td>@Html.LabelFor(m => m.PumpNum)@Html.TextBoxFor(m => m.PumpNum, new { Value = 0 })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.PumpPrice)@Html.EditorFor(m => m.PumpPrice)</td>
 
        <td>@Html.LabelFor(m => m.PumpSum)@Html.TextBoxFor(m => m.PumpSum, new { readOnly = true })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.BeginDate)@Html.EditorFor(m => m.BeginDate,"DateTime")</td>
 
        <td>@Html.LabelFor(m => m.EndDate)@Html.EditorFor(m => m.EndDate,"DateTime")</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.SlurryCustNum)@Html.TextBoxFor(m => m.SlurryCustNum, new { Value = 0 })</td>
 
        <td>@Html.LabelFor(m => m.SlurryPumpNum)@Html.EditorFor(m => m.SlurryPumpNum)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.SlurryPumpPrice)@Html.EditorFor(m => m.SlurryPumpPrice)</td>
 
        <td>@Html.LabelFor(m => m.SlurryPumpSum)@Html.TextBoxFor(m => m.SlurryPumpSum, new { readOnly = true })</td>
   
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.Credit)@Html.TextBoxFor(m => m.Credit, new { readOnly = true })</td>
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.Remark)@Html.TextAreaFor(m => m.Remark, 4, 58, new { @class = "text" })</td>
    </tr>
</table>

}
</div>

@*编辑*@
<div id="pumpworkeditform" class="mvcform" style=" display:none;">
@using (Html.BeginForm())
{ 
    @Html.ValidationSummary()
<table class="mvcform"> 
    <tr> 
        <td>@Html.TextBoxFor(m => m.ID, new { @class = "text", style = "display:none;" })
        @Html.LabelFor(m => m.Customer.CustName)@Html.TextBoxFor(m => m.CustomerID, new { @class = "text", id = "CustomerID_EDIT", disabled = true })
        </td>
        <td>@Html.LabelFor(m => m.Saler)@Html.EditorFor(m => m.Saler)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.Contract.ContractName)@Html.TextBoxFor(m => m.ContractID, new { @class = "text", id = "ContractID_EDIT", style = "width:137px;", disabled = true })</td>
 
        <td>@Html.LabelFor(m => m.PumpDate)@Html.EditorFor(m => m.PumpDate, "DateTime", new { defaultValue = @DateTime.Now.ToString("yyyy-MM-dd"), id = "PumpDate_EDIT" })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.TaskID)@Html.TextBoxFor(m => m.TaskID, new { @class = "text", id = "TaskID_EDIT", style = "width:137px;", readOnly = true })</td>
 
        <td>@Html.LabelFor(m => m.PumpType)@Html.DicEidtor("PumpType","PumpType_EDIT", DicEnum.PumpType)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.CarID)@Html.DropDownListFor(m => m.CarID, Enumerable.Empty<SelectListItem>(), new { @class = "text", style = "width:137px;", id ="CarID_EDIT"})</td>
 
        <td>@Html.LabelFor(m => m.Driver)@Html.EditorFor(m => m.Driver)</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.CustNum)@Html.TextBoxFor(m => m.CustNum, new { id = "CustNum_EDIT", Value = 0 })</td>
 
        <td>@Html.LabelFor(m => m.PumpNum)@Html.TextBoxFor(m => m.PumpNum, new { id = "PumpNum_EDIT", Value = 0 })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.PumpPrice)@Html.TextBoxFor(m => m.PumpPrice, new { id = "PumpPrice_EDIT" })</td>
 
        <td>@Html.LabelFor(m => m.PumpSum)@Html.TextBoxFor(m => m.PumpSum, new { id = "PumpSum_EDIT", readOnly = true })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.BeginDate)@Html.EditorFor(m => m.BeginDate, "DateTime", new { id = "BeginDate_EDIT" })</td>
 
        <td>@Html.LabelFor(m => m.EndDate)@Html.EditorFor(m => m.EndDate, "DateTime", new { id = "EndDate_EDIT" })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.SlurryCustNum)@Html.TextBoxFor(m => m.SlurryCustNum, new { id = "SlurryCustNum_EDIT", Value = 0 })</td>
 
        <td>@Html.LabelFor(m => m.SlurryPumpNum)@Html.TextBoxFor(m => m.SlurryPumpNum, new { id = "SlurryPumpNum_EDIT" })</td>
   
    </tr>
    <tr> 
        <td>@Html.LabelFor(m => m.SlurryPumpPrice)@Html.TextBoxFor(m => m.SlurryPumpPrice, new { id = "SlurryPumpPrice_EDIT" })</td>
 
        <td>@Html.LabelFor(m => m.SlurryPumpSum)@Html.TextBoxFor(m => m.SlurryPumpSum, new { id = "SlurryPumpSum_EDIT", readOnly = true })</td>
   
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.Credit)@Html.TextBoxFor(m => m.Credit, new { id = "Credit_EDIT", readOnly = true })</td>
    </tr>
    <tr> 
        <td colspan="2">@Html.LabelFor(m => m.Remark)@Html.TextAreaFor(m => m.Remark, 4, 58, new { @class = "text" })</td>
    </tr>
</table>

}
</div>